In [21]:
import os, fnmatch, glob, re
import pandas as pd

In [23]:
os.getcwd()                                 # 查看目前工作目錄

'D:\\JupyterNotebook\\data_analysis'

In [24]:
path = "./C-MAPSS"
fnames = os.listdir(path); fnames          # 列出C-MAPSS裡所有的檔案

['description.txt',
 'Icon_',
 'Image_001.png',
 'Image_002.png',
 'ReadMe.pdf',
 'readme.txt',
 'RUL_FD001.txt',
 'RUL_FD002.txt',
 'RUL_FD003.txt',
 'RUL_FD004.txt',
 'test_FD001.txt',
 'test_FD002.txt',
 'test_FD003.txt',
 'test_FD004.txt',
 'train_FD001.txt',
 'train_FD002.txt',
 'train_FD003.txt',
 'train_FD004.txt']

In [25]:
pattern1 = "train*"
for file in fnames:
    if fnmatch.fnmatch(file, pattern1):
        print(file)

train_FD001.txt
train_FD002.txt
train_FD003.txt
train_FD004.txt

In [42]:
files = [i for i in glob.glob('./C-MAPSS/train*.txt')]          # glob()可以輸入路徑
files

['./C-MAPSS\\train_FD001.txt',
 './C-MAPSS\\train_FD002.txt',
 './C-MAPSS\\train_FD003.txt',
 './C-MAPSS\\train_FD004.txt']

In [43]:
trains = [pd.read_csv(f, sep = ' ', header = None, usecols = range(26), names = colnames) for f in files]; trains

[       unitNo  cycles  opera1  opera2  opera3      T2     T24      T30  \
 0           1       1 -0.0007 -0.0004   100.0  518.67  641.82  1589.70
 1           1       2  0.0019 -0.0003   100.0  518.67  642.15  1591.82
 2           1       3 -0.0043  0.0003   100.0  518.67  642.35  1587.99
 3           1       4  0.0007  0.0000   100.0  518.67  642.35  1582.79
 4           1       5 -0.0019 -0.0002   100.0  518.67  642.37  1582.85
 ...       ...     ...     ...     ...     ...     ...     ...      ...
 20626     100     196 -0.0004 -0.0003   100.0  518.67  643.49  1597.98
 20627     100     197 -0.0016 -0.0005   100.0  518.67  643.54  1604.50
 20628     100     198  0.0004  0.0000   100.0  518.67  643.42  1602.46
 20629     100     199 -0.0011  0.0003   100.0  518.67  643.23  1605.26
 20630     100     200 -0.0032 -0.0005   100.0  518.67  643.85  1600.38

            T50     P2  ...     phi      NRf      NRc     BPR  farB  htBleed  \
 0      1400.60  14.62  ...  521.66  2388.02  8138.62  8.4195  0.03      392
 1      1403.14  14.62  ...  522.28  2388.07  8131.49  8.4318  0.03      392
 2      1404.20  14.62  ...  522.42  2388.03  8133.23  8.4178  0.03      390
 3      1401.87  14.62  ...  522.86  2388.08  8133.83  8.3682  0.03      392
 4      1406.22  14.62  ...  522.19  2388.04  8133.80  8.4294  0.03      393
 ...        ...    ...  ...     ...      ...      ...     ...   ...      ...
 20626  1428.63  14.62  ...  519.49  2388.26  8137.60  8.4956  0.03      397
 20627  1433.58  14.62  ...  519.68  2388.22  8136.50  8.5139  0.03      395
 20628  1428.18  14.62  ...  520.01  2388.24  8141.05  8.5646  0.03      398
 20629  1426.53  14.62  ...  519.67  2388.23  8139.29  8.5389  0.03      395
 20630  1432.14  14.62  ...  519.30  2388.26  8137.33  8.5036  0.03      396

        Nf_dmd  PCNfr_dmd    W31      W32
 0        2388      100.0  39.06  23.4190
 1        2388      100.0  39.00  23.4236
 2        2388      100.0  38.95  23.3442
 3        2388      100.0  38.88  23.3739
 4        2388      100.0  38.90  23.4044
 ...       ...        ...    ...      ...
 20626    2388      100.0  38.49  22.9735
 20627    2388      100.0  38.30  23.1594
 20628    2388      100.0  38.44  22.9333
 20629    2388      100.0  38.29  23.0640
 20630    2388      100.0  38.37  23.0522

 [20631 rows x 26 columns],
        unitNo  cycles   opera1  opera2  opera3      T2     T24      T30  \
 0           1       1  34.9983  0.8400   100.0  449.44  555.32  1358.61
 1           1       2  41.9982  0.8408   100.0  445.00  549.90  1353.22
 2           1       3  24.9988  0.6218    60.0  462.54  537.31  1256.76
 3           1       4  42.0077  0.8416   100.0  445.00  549.51  1354.03
 4           1       5  25.0005  0.6203    60.0  462.54  537.07  1257.71
 ...       ...     ...      ...     ...     ...     ...     ...      ...
 53754     260     312  20.0037  0.7000   100.0  491.19  608.79  1495.60
 53755     260     313  10.0022  0.2510   100.0  489.05  605.81  1514.32
 53756     260     314  25.0041  0.6200    60.0  462.54  537.48  1276.24
 53757     260     315  25.0033  0.6220    60.0  462.54  537.84  1272.95
 53758     260     316  35.0036  0.8400   100.0  449.44  556.64  1374.61

            T50     P2  ...     phi      NRf      NRc      BPR  farB  htBleed  \
 0      1137.23   5.48  ...  183.06  2387.72  8048.56   9.3461  0.02      334
 1      1125.78   3.91  ...  130.42  2387.66  8072.30   9.3774  0.02      330
 2      1047.45   7.05  ...  164.22  2028.03  7864.87  10.8941  0.02      309
 3      1126.38   3.91  ...  130.72  2387.61  8068.66   9.3528  0.02      329
 4      1047.93   7.05  ...  164.31  2028.00  7861.23  10.8963  0.02      309
 ...        ...    ...  ...     ...      ...      ...      ...   ...      ...
 53754  1269.51   9.35  ...  314.05  2389.02  8169.64   9.3035  0.03      369
 53755  1324.12  10.52  ...  371.22  2388.42  8245.36   8.7586  0.03      374
 53756  1057.92   7.05  ...  163.74  2030.33  7971.25  11.0657  0.02      310
 53757  1066.30   7.05  ...  164.37  2030.35  7972.47  11.0537  0.02      311
 53758  1145.52   5.48  ...  183.09  2390.38  8185.35   9.3998  0.02      338

        Nf_dmd  PCNfr_dmd    W31      W32
 0        2223     100.00  14.73   8.8071
 1        2212     100.00  10.41   6.2665
 2        1915      84.93  14.08   8.6723
 3        2212     100.00  10.59   6.4701
 4        1915      84.93  14.13   8.5286
 ...       ...        ...    ...      ...
 53754    2324     100.00  24.36  14.5189
 53755    2319     100.00  28.10  16.9454
 53756    1915      84.93  14.19   8.5503
 53757    1915      84.93  14.05   8.3729
 53758    2223     100.00  14.75   8.8446

 [53759 rows x 26 columns],
        unitNo  cycles  opera1  opera2  opera3      T2     T24      T30  \
 0           1       1 -0.0005  0.0004   100.0  518.67  642.36  1583.23
 1           1       2  0.0008 -0.0003   100.0  518.67  642.50  1584.69
 2           1       3 -0.0014 -0.0002   100.0  518.67  642.18  1582.35
 3           1       4 -0.0020  0.0001   100.0  518.67  642.92  1585.61
 4           1       5  0.0016  0.0000   100.0  518.67  641.68  1588.63
 ...       ...     ...     ...     ...     ...     ...     ...      ...
 24715     100     148 -0.0016 -0.0003   100.0  518.67  643.78  1596.01
 24716     100     149  0.0034 -0.0003   100.0  518.67  643.29  1596.38
 24717     100     150 -0.0016  0.0004   100.0  518.67  643.84  1604.53
 24718     100     151 -0.0023  0.0004   100.0  518.67  643.94  1597.56
 24719     100     152  0.0000  0.0003   100.0  518.67  643.64  1599.04

            T50     P2  ...     phi      NRf      NRc     BPR  farB  htBleed  \
 0      1396.84  14.62  ...  522.31  2388.01  8145.32  8.4246  0.03      391
 1      1396.89  14.62  ...  522.42  2388.03  8152.85  8.4403  0.03      392
 2      1405.61  14.62  ...  522.03  2388.00  8150.17  8.3901  0.03      391
 3      1392.27  14.62  ...  522.49  2388.08  8146.56  8.3878  0.03      392
 4      1397.65  14.62  ...  522.58  2388.03  8147.80  8.3869  0.03      392
 ...        ...    ...  ...     ...      ...      ...     ...   ...      ...
 24715  1424.11  14.62  ...  519.66  2388.30  8138.08  8.5036  0.03      394
 24716  1429.14  14.62  ...  519.91  2388.28  8144.36  8.5174  0.03      395
 24717  1431.41  14.62  ...  519.44  2388.24  8135.95  8.5223  0.03      396
 24718  1426.57  14.62  ...  520.01  2388.26  8141.24  8.5148  0.03      395
 24719  1436.06  14.62  ...  519.48  2388.24  8136.98  8.5150  0.03      396

        Nf_dmd  PCNfr_dmd    W31      W32
 0        2388      100.0  39.11  23.3537
 1        2388      100.0  38.99  23.4491
 2        2388      100.0  38.85  23.3669
 3        2388      100.0  38.96  23.2951
 4        2388      100.0  39.14  23.4583
 ...       ...        ...    ...      ...
 24715    2388      100.0  38.44  22.9631
 24716    2388      100.0  38.50  22.9746
 24717    2388      100.0  38.39  23.0682
 24718    2388      100.0  38.31  23.0753
 24719    2388      100.0  38.56  23.0847

 [24720 rows x 26 columns],
        unitNo  cycles   opera1  opera2  opera3      T2     T24      T30  \
 0           1       1  42.0049  0.8400   100.0  445.00  549.68  1343.43
 1           1       2  20.0020  0.7002   100.0  491.19  606.07  1477.61
 2           1       3  42.0038  0.8409   100.0  445.00  548.95  1343.12
 3           1       4  42.0000  0.8400   100.0  445.00  548.70  1341.24
 4           1       5  25.0063  0.6207    60.0  462.54  536.10  1255.23
 ...       ...     ...      ...     ...     ...     ...     ...      ...
 61244     249     251   9.9998  0.2500   100.0  489.05  605.33  1516.36
 61245     249     252   0.0028  0.0015   100.0  518.67  643.42  1598.92
 61246     249     253   0.0029  0.0000   100.0  518.67  643.68  1607.72
 61247     249     254  35.0046  0.8400   100.0  449.44  555.77  1381.29
 61248     249     255  42.0030  0.8400   100.0  445.00  549.85  1369.75

            T50     P2  ...     phi      NRf      NRc      BPR  farB  htBleed  \
 0      1112.93   3.91  ...  129.78  2387.99  8074.83   9.3335  0.02      330
 1      1237.50   9.35  ...  312.59  2387.73  8046.13   9.1913  0.02      361
 2      1117.05   3.91  ...  129.62  2387.97  8066.62   9.4007  0.02      329
 3      1118.03   3.91  ...  129.80  2388.02  8076.05   9.3369  0.02      328
 4      1033.59   7.05  ...  164.11  2028.08  7865.80  10.8366  0.02      305
 ...        ...    ...  ...     ...      ...      ...      ...   ...      ...
 61244  1315.28  10.52  ...  380.16  2388.73  8185.69   8.4541  0.03      372
 61245  1426.77  14.62  ...  535.02  2388.46  8185.47   8.2221  0.03      396
 61246  1430.56  14.62  ...  535.41  2388.48  8193.94   8.2525  0.03      395
 61247  1148.18   5.48  ...  187.92  2388.83  8125.64   9.0515  0.02      337
 61248  1147.45   3.91  ...  134.32  2388.66  8144.33   9.1207  0.02      333

        Nf_dmd  PCNfr_dmd    W31      W32
 0        2212     100.00  10.62   6.3670
 1        2324     100.00  24.37  14.6552
 2        2212     100.00  10.48   6.4213
 3        2212     100.00  10.54   6.4176
 4        1915      84.93  14.03   8.6754
 ...       ...        ...    ...      ...
 61244    2319     100.00  29.11  17.5234
 61245    2388     100.00  39.38  23.7151
 61246    2388     100.00  39.78  23.8270
 61247    2223     100.00  15.26   9.0774
 61248    2212     100.00  10.66   6.4341

 [61249 rows x 26 columns]]

In [44]:
train1 = pd.read_csv(files[1], sep = ' ', header = None); train1

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,1,1,34.9983,0.8400,100.0,449.44,555.32,1358.61,1137.23,5.48,...,8048.56,9.3461,0.02,334,2223,100.00,14.73,8.8071,NaN,NaN
1,1,2,41.9982,0.8408,100.0,445.00,549.90,1353.22,1125.78,3.91,...,8072.30,9.3774,0.02,330,2212,100.00,10.41,6.2665,NaN,NaN
2,1,3,24.9988,0.6218,60.0,462.54,537.31,1256.76,1047.45,7.05,...,7864.87,10.8941,0.02,309,1915,84.93,14.08,8.6723,NaN,NaN
3,1,4,42.0077,0.8416,100.0,445.00,549.51,1354.03,1126.38,3.91,...,8068.66,9.3528,0.02,329,2212,100.00,10.59,6.4701,NaN,NaN
4,1,5,25.0005,0.6203,60.0,462.54,537.07,1257.71,1047.93,7.05,...,7861.23,10.8963,0.02,309,1915,84.93,14.13,8.5286,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53754,260,312,20.0037,0.7000,100.0,491.19,608.79,1495.60,1269.51,9.35,...,8169.64,9.3035,0.03,369,2324,100.00,24.36,14.5189,NaN,NaN
53755,260,313,10.0022,0.2510,100.0,489.05,605.81,1514.32,1324.12,10.52,...,8245.36,8.7586,0.03,374,2319,100.00,28.10,16.9454,NaN,NaN
53756,260,314,25.0041,0.6200,60.0,462.54,537.48,1276.24,1057.92,7.05,...,7971.25,11.0657,0.02,310,1915,84.93,14.19,8.5503,NaN,NaN
53757,260,315,25.0033,0.6220,60.0,462.54,537.84,1272.95,1066.30,7.05,...,7972.47,11.0537,0.02,311,1915,84.93,14.05,8.3729,NaN,NaN
53758,260,316,35.0036,0.8400,100.0,449.44,556.64,1374.61,1145.52,5.48,...,8185.35,9.3998,0.02,338,2223,100.00,14.75,8.8446,NaN,NaN

In [48]:
colnames = ["unitNo", "cycles","opera1","opera2","opera3","T2","T24","T30","T50","P2","P15","P30","Nf","Nc","epr","Ps30","phi","NRf","NRc","BPR","farB","htBleed","Nf_dmd","PCNfr_dmd","W31","W32"]
train1 = pd.read_csv(files[1], sep = ' ', header = None, usecols = range(26), names = colnames); train1

,unitNo,cycles,opera1,opera2,opera3,T2,T24,T30,T50,P2,...,phi,NRf,NRc,BPR,farB,htBleed,Nf_dmd,PCNfr_dmd,W31,W32
0,1,1,34.9983,0.8400,100.0,449.44,555.32,1358.61,1137.23,5.48,...,183.06,2387.72,8048.56,9.3461,0.02,334,2223,100.00,14.73,8.8071
1,1,2,41.9982,0.8408,100.0,445.00,549.90,1353.22,1125.78,3.91,...,130.42,2387.66,8072.30,9.3774,0.02,330,2212,100.00,10.41,6.2665
2,1,3,24.9988,0.6218,60.0,462.54,537.31,1256.76,1047.45,7.05,...,164.22,2028.03,7864.87,10.8941,0.02,309,1915,84.93,14.08,8.6723
3,1,4,42.0077,0.8416,100.0,445.00,549.51,1354.03,1126.38,3.91,...,130.72,2387.61,8068.66,9.3528,0.02,329,2212,100.00,10.59,6.4701
4,1,5,25.0005,0.6203,60.0,462.54,537.07,1257.71,1047.93,7.05,...,164.31,2028.00,7861.23,10.8963,0.02,309,1915,84.93,14.13,8.5286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53754,260,312,20.0037,0.7000,100.0,491.19,608.79,1495.60,1269.51,9.35,...,314.05,2389.02,8169.64,9.3035,0.03,369,2324,100.00,24.36,14.5189
53755,260,313,10.0022,0.2510,100.0,489.05,605.81,1514.32,1324.12,10.52,...,371.22,2388.42,8245.36,8.7586,0.03,374,2319,100.00,28.10,16.9454
53756,260,314,25.0041,0.6200,60.0,462.54,537.48,1276.24,1057.92,7.05,...,163.74,2030.33,7971.25,11.0657,0.02,310,1915,84.93,14.19,8.5503
53757,260,315,25.0033,0.6220,60.0,462.54,537.84,1272.95,1066.30,7.05,...,164.37,2030.35,7972.47,11.0537,0.02,311,1915,84.93,14.05,8.3729
53758,260,316,35.0036,0.8400,100.0,449.44,556.64,1374.61,1145.52,5.48,...,183.09,2390.38,8185.35,9.3998,0.02,338,2223,100.00,14.75,8.8446

In [47]:
# 把所有資料合併在一起
train_all = pd.concat(trains); train_all

,unitNo,cycles,opera1,opera2,opera3,T2,T24,T30,T50,P2,...,phi,NRf,NRc,BPR,farB,htBleed,Nf_dmd,PCNfr_dmd,W31,W32
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61244,249,251,9.9998,0.2500,100.0,489.05,605.33,1516.36,1315.28,10.52,...,380.16,2388.73,8185.69,8.4541,0.03,372,2319,100.0,29.11,17.5234
61245,249,252,0.0028,0.0015,100.0,518.67,643.42,1598.92,1426.77,14.62,...,535.02,2388.46,8185.47,8.2221,0.03,396,2388,100.0,39.38,23.7151
61246,249,253,0.0029,0.0000,100.0,518.67,643.68,1607.72,1430.56,14.62,...,535.41,2388.48,8193.94,8.2525,0.03,395,2388,100.0,39.78,23.8270
61247,249,254,35.0046,0.8400,100.0,449.44,555.77,1381.29,1148.18,5.48,...,187.92,2388.83,8125.64,9.0515,0.02,337,2223,100.0,15.26,9.0774
61248,249,255,42.0030,0.8400,100.0,445.00,549.85,1369.75,1147.45,3.91,...,134.32,2388.66,8144.33,9.1207,0.02,333,2212,100.0,10.66,6.4341